"""Generate real access codes + real dealer data for the Training Hub chat.

Reads the two client sheets:
  data/employees.xlsx  (Legal_Firstname, Legal_Lastname, Position, Work_Location)
  data/dealers.xlsx    (Customer ID, Customer Name, Sales Rep Name (Cust))

and produces:
  chat_bot/chat_config/tm_keys.yaml        one key per TM who has program dealers,
                                           plus all-territory keys for leadership
  chat_bot/chat_config/trainer_codes.yaml  John Ward + the Field Service Reps
  chat_bot/data_global/dealers_sim.csv     the 200+ REAL program dealers
  chat_bot/data_global/registrations_sim.csv  simulated training history over the
                                           real dealers (until real attendance
                                           tracking lands — Phase C)
  data/access_codes.xlsx                   the handout sheet for John

Scoping trick: TMs are not branch-scoped (one branch serves many TMs), so each
dealer's `branch` column carries its TM's full name and each TM key lists only
that name in `branches`. Leadership keys list every TM name + "House Accounts".

Codes are deterministic (sha1 of name+role), so re-running never reshuffles
codes that were already handed out. Not everyone gets a code on purpose.

Run:  ./.venv/bin/python tools/make_codes.py
"""
import csv
import hashlib
import random
import sys
from pathlib import Path

from openpyxl import Workbook, load_workbook

ROOT = Path(__file__).resolve().parent.parent
sys.path.insert(0, str(ROOT))

DATA = ROOT / "data"
CHAT = ROOT / "chat_bot"

from src.dealers import REP_ALIASES  # noqa: E402  (one canonical alias map)

HOUSE_REPS = {"Birmingham House", "Memphis House"}
LEADERSHIP_POSITIONS = {"Chief Executive Officer", "President", "Regional Sales Manager"}
TRAINER_POSITIONS = {"Director of Training & Technical Services", "Field Service Representative"}


def code_for(name, prefix):
    digits = int(hashlib.sha1(f"{prefix}:{name}".encode()).hexdigest(), 16) % 9000 + 1000
    last = name.split()[-1].upper()
    return f"{prefix}-{last}-{digits}"


def flip(rep):
    last, _, first = str(rep).partition(",")
    return f"{first.strip()} {last.strip()}".title() if "," in str(rep) else str(rep).title()


def slug(name):
    return "tm_" + "_".join(name.lower().split())


def read_employees():
    wb = load_workbook(DATA / "employees.xlsx", read_only=True)
    rows = [r for r in wb.active.iter_rows(min_row=2, values_only=True) if r[0]]
    wb.close()
    return [{"name": f"{r[0]} {r[1]}".title(), "position": str(r[2] or "").strip(),
             "location": str(r[3] or "").strip()} for r in rows]


def read_dealers():
    wb = load_workbook(DATA / "dealers.xlsx", read_only=True)
    out, seen = [], False
    for r in wb.active.iter_rows(values_only=True):
        if not seen:
            seen = str(r[0] or "").strip() == "Customer ID"
            continue
        if r[0] is None or not str(r[1] or "").strip():
            continue
        out.append({"customer_id": str(r[0]).strip(), "name": str(r[1]).strip(),
                    "rep": flip(r[2]) if r[2] else ""})
    wb.close()
    return out


def main():
    employees = read_employees()
    dealers = read_dealers()
    by_position = {}
    for e in employees:
        by_position.setdefault(e["position"], []).append(e)

    tms = {e["name"]: e for e in by_position.get("Territory Manager", [])}

    # group real dealers under their TM (legal name); house accounts stay separate
    dealers_by_tm = {}
    for d in dealers:
        rep = REP_ALIASES.get(d["rep"], d["rep"])
        owner = "House Accounts" if d["rep"] in HOUSE_REPS else rep
        dealers_by_tm.setdefault(owner, []).append(d)

    active_tms = [n for n in dealers_by_tm if n in tms]            # has dealers AND is a TM
    skipped = sorted(set(tms) - set(active_tms))                   # TM, but no program dealers

    # ---- tm_keys.yaml ----------------------------------------------------------
    lines = [
        "# Territory Manager access keys — REAL TMs from the employee list",
        "# (06.01.2026), scoped to their REAL program dealers (dealers.xlsx).",
        "# A dealer's `branch` column carries the TM's name, so `branches` below",
        "# is a name list, not branch codes. Generated by tools/make_codes.py —",
        "# edit that script, not this file. TMs with no program dealers get no key.",
        "",
        "tms:",
    ]
    tm_rows = []
    for name in sorted(active_tms):
        key = code_for(name, "TM")
        lines += [
            f"  {slug(name)}:",
            f'    key: "{key}"',
            f'    display_name: "{name} — {tms[name]["location"]}"',
            "    branches:",
            f'      - "{name}"',
            '    temp_folder: ""',
            "",
        ]
        tm_rows.append((name, tms[name]["location"], key, len(dealers_by_tm[name])))

    leadership = sorted((e for p in LEADERSHIP_POSITIONS for e in by_position.get(p, [])),
                        key=lambda e: e["name"])
    all_scopes = sorted(active_tms) + ["House Accounts"]
    lead_rows = []
    lines += ["  # Leadership — every territory + house accounts"]
    for e in leadership:
        key = code_for(e["name"], "EXEC")
        lines += [
            f"  {slug(e['name'])}:",
            f'    key: "{key}"',
            f'    display_name: "{e["name"]} — All Territories ({e["position"]})"',
            "    branches:",
            *[f'      - "{s}"' for s in all_scopes],
            '    temp_folder: ""',
            "",
        ]
        lead_rows.append((e["name"], e["position"], key, len(dealers)))
    (CHAT / "chat_config" / "tm_keys.yaml").write_text("\n".join(lines), encoding="utf-8")

    # ---- trainer_codes.yaml ----------------------------------------------------
    with (CHAT / "data_global" / "classes_sim.csv").open(newline="", encoding="utf-8") as f:
        topics = sorted({r["topic"] for r in csv.DictReader(f)})
    trainers = sorted((e for p in TRAINER_POSITIONS for e in by_position.get(p, [])),
                      key=lambda e: (e["position"] != "Director of Training & Technical Services",
                                     e["name"]))
    lines = [
        "# Trainer access codes — REAL trainers from the employee list: the Director",
        "# of Training + Field Service Reps. All topics for everyone until a real",
        "# trainer→class schedule exists (Phase C). Generated by tools/make_codes.py.",
        "",
        "trainers:",
    ]
    trainer_rows = []
    for e in trainers:
        code = code_for(e["name"], "TRAIN")
        lines += [
            f"  trainer_{e['name'].split()[-1].lower()}:",
            f'    code: "{code}"',
            f'    display_name: "{e["name"]}"',
            "    topics:",
            *[f'      - "{t}"' for t in topics],
            "",
        ]
        trainer_rows.append((e["name"], e["position"], code))
    (CHAT / "chat_config" / "trainer_codes.yaml").write_text("\n".join(lines), encoding="utf-8")

    # ---- dealers_sim.csv (REAL dealers) ----------------------------------------
    with (CHAT / "data_global" / "dealers_sim.csv").open("w", newline="", encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["dealer_id", "dealer_name", "branch", "tm_id", "tier",
                    "primary_contact", "contact_email"])
        for owner, ds in sorted(dealers_by_tm.items()):
            tm_id = slug(owner) if owner in tms else "house"
            for d in sorted(ds, key=lambda x: x["name"]):
                w.writerow([d["customer_id"], d["name"], owner, tm_id,
                            "2026 Program", "", ""])

    # ---- registrations_sim.csv (sim history over real dealers) ------------------
    with (CHAT / "data_global" / "classes_sim.csv").open(newline="", encoding="utf-8") as f:
        classes = list(csv.DictReader(f))
    rng = random.Random(42)
    first = ["James", "Maria", "Chris", "Dana", "Alex", "Tyler", "Sam", "Jordan",
             "Casey", "Luis", "Tony", "Rachel"]
    last = ["Hayes", "Lopez", "Vance", "Frye", "Marsh", "Dill", "Stone", "Berry",
            "Cole", "Ortiz", "Lane", "Webb"]
    roles = ["Technician", "Inside Sales", "Outside Sales", "Owner"]
    rows, n = [], 0
    seats = {c["event_id"]: 0 for c in classes}   # keep sim class sizes realistic
    for owner, ds in sorted(dealers_by_tm.items()):
        tm_id = slug(owner) if owner in tms else "house"
        for d in sorted(ds, key=lambda x: x["name"]):
            for _ in range(rng.choice([0, 0, 1, 1, 1, 2, 2, 3])):   # ~40% have history
                open_c = [c for c in classes
                          if seats[c["event_id"]] < int(c.get("capacity") or 16)]
                if not open_c:
                    break
                c = rng.choice(open_c)
                seats[c["event_id"]] += 1
                attended = rng.random() < 0.8
                score = rng.randint(48, 98) if attended else 0
                status = ("Completed" if attended and score >= 70
                          else "No Show" if not attended and rng.random() < 0.5
                          else "In Progress")
                n += 1
                rows.append([f"r{n:04d}", c["event_id"], d["customer_id"],
                             f"{rng.choice(first)} {rng.choice(last)}", rng.choice(roles),
                             owner, tm_id, c["level"], "yes" if attended else "no",
                             score, status, c["event_date"]])
    with (CHAT / "data_global" / "registrations_sim.csv").open("w", newline="",
                                                               encoding="utf-8") as f:
        w = csv.writer(f)
        w.writerow(["reg_id", "event_id", "dealer_id", "attendee_name", "role", "branch",
                    "tm_id", "level", "attended", "score", "status", "reg_date"])
        w.writerows(rows)

    # ---- access_codes.xlsx (handout for John) -----------------------------------
    wb = Workbook()
    ws = wb.active
    ws.title = "TM Codes"
    ws.append(["Territory Manager", "Location", "Access Code", "Program Dealers"])
    for r in tm_rows:
        ws.append(list(r))
    ws2 = wb.create_sheet("Trainer Codes")
    ws2.append(["Trainer", "Position", "Access Code"])
    for r in trainer_rows:
        ws2.append(list(r))
    ws3 = wb.create_sheet("Leadership")
    ws3.append(["Name", "Position", "Access Code", "Sees All Dealers"])
    for r in lead_rows:
        ws3.append(list(r))
    for sheet in wb.worksheets:
        for col in sheet.columns:
            width = max(len(str(c.value or "")) for c in col) + 3
            sheet.column_dimensions[col[0].column_letter].width = width
    wb.save(DATA / "access_codes.xlsx")

    print(f"TM keys: {len(tm_rows)}  (no dealers, no key: {', '.join(skipped) or '—'})")
    print(f"Trainer codes: {len(trainer_rows)}   Leadership keys: {len(lead_rows)}")
    print(f"Dealers written: {len(dealers)}   Sim history rows: {len(rows)}")
    print(f"Handout: {DATA / 'access_codes.xlsx'}")


if __name__ == "__main__":
    main()
