"""ADMIN-HUB backend: code login + read-only class/roster views for staff.

Three roles, all resolved from the SAME access codes the Training Assistant uses
(chat_bot/chat_config/*.yaml — one source of truth, regenerated by
tools/make_codes.py):

  teacher  TRAIN-… codes   sees every class + editable-looking grade sheet
                           (saving is intentionally disabled — demo session)
  staff    EXEC-…  keys    view-only, all regions, region filter in the UI
  tm       TM-…    keys    view-only, scoped to registrations whose Territory
                           Manager is them (real dealer mapping)

Grades/attendance are NOT persisted anywhere yet — that's the paid build.
Everything here is read-only against the live catalog + registrations DB.
"""
import sqlite3
from datetime import date

import yaml

from config import DB_PATH, HERE
from src.catalog import is_active, load_catalog

_CHAT_CONFIG = HERE / "chat_bot" / "chat_config"


def _load_yaml(name):
    path = _CHAT_CONFIG / name
    if not path.exists():
        return {}
    return yaml.safe_load(path.read_text(encoding="utf-8")) or {}


# Master demo codes (case-insensitive) — what John actually types in the room.
# Per-person codes from data/access_codes.xlsx keep working alongside these.
MASTER_CODES = {
    "MAINS": {"role": "teacher", "id": "trainer_ward",
              "display_name": "Instructor — John Ward", "scope": []},
    "MATMPLUS": {"role": "tm", "id": "tm_micah_shelton", "demo": True,
                 "display_name": "Territory Manager — Micah Shelton (demo)",
                 "scope": ["Micah Shelton"]},
    "MAFULL": {"role": "staff", "id": "ma_employee",
               "display_name": "M&A Employee — Full View", "scope": []},
}


def admin_login(code):
    """Resolve an access code to a role descriptor, or None."""
    code = str(code or "").strip().upper()
    if not code:
        return None
    if code in MASTER_CODES:
        session = dict(MASTER_CODES[code])
        if session["role"] == "tm" and session.get("demo"):
            roster = []
            for cfg in (_load_yaml("tm_keys.yaml").get("tms") or {}).values():
                scope = cfg.get("branches") or []
                display = cfg.get("display_name", "")
                if len(scope) == 1 and "—" in display:
                    roster.append({"name": scope[0],
                                   "location": display.split("—")[-1].strip()})
            session["pick"] = sorted(roster, key=lambda x: x["name"])
        return session
    for tid, cfg in (_load_yaml("trainer_codes.yaml").get("trainers") or {}).items():
        if cfg.get("code", "").upper() == code:
            return {"role": "teacher", "id": tid,
                    "display_name": cfg.get("display_name", tid), "scope": []}
    for tmid, cfg in (_load_yaml("tm_keys.yaml").get("tms") or {}).items():
        if cfg.get("key", "").upper() == code:
            scope = list(cfg.get("branches") or [])
            display = cfg.get("display_name", tmid)
            # leadership keys span every territory; real TMs are scoped to one name
            role = "staff" if len(scope) > 1 else "tm"
            return {"role": role, "id": tmid, "display_name": display, "scope": scope}
    return None


def _con():
    con = sqlite3.connect(DB_PATH)
    con.row_factory = sqlite3.Row
    con.execute("""CREATE TABLE IF NOT EXISTS class_log (
        event_id TEXT PRIMARY KEY, surveys_sent_at TEXT)""")
    con.execute("""CREATE TABLE IF NOT EXISTS nudge_log (
        id INTEGER PRIMARY KEY, company TEXT, tm_id TEXT, nudge_type TEXT, sent_at TEXT)""")
    return con


def log_nudge(session, company, nudge_type):
    """Audit trail under the at-risk table: 'Nudge sent for X on DATE'."""
    from datetime import datetime
    sent_at = datetime.now().strftime("%b %d, %Y · %H:%M")
    con = _con()
    con.execute("INSERT INTO nudge_log (company, tm_id, nudge_type, sent_at) VALUES (?,?,?,?)",
                (company, session["id"], nudge_type, sent_at))
    con.commit()
    con.close()
    return {"ok": True, "sent_at": sent_at}


def mark_surveys_sent(session, event_id):
    """Step 2 audit mark: 'Surveys & quizzes sent on {date}' — also what keeps
    the button from being spam-clicked."""
    if session["role"] != "teacher":
        return {"ok": False, "error": "Only trainers can send class surveys."}
    from datetime import datetime
    sent_at = datetime.now().strftime("%b %d, %Y · %H:%M")
    con = _con()
    con.execute("""INSERT INTO class_log (event_id, surveys_sent_at) VALUES (?,?)
                   ON CONFLICT(event_id) DO UPDATE SET surveys_sent_at=excluded.surveys_sent_at""",
                (event_id, sent_at))
    con.commit()
    con.close()
    return {"ok": True, "sent_at": sent_at}


def _real_tm_names():
    """The program TMs (single-territory keys)."""
    return [cfg["branches"][0]
            for cfg in (_load_yaml("tm_keys.yaml").get("tms") or {}).values()
            if len(cfg.get("branches") or []) == 1]


def _tm_home_region(name):
    """A TM's home location (from the key display 'Name — Location')."""
    for cfg in (_load_yaml("tm_keys.yaml").get("tms") or {}).values():
        scope = cfg.get("branches") or []
        display = cfg.get("display_name", "")
        if scope == [name] and "—" in display:
            return display.split("—")[-1].strip()
    return ""


def _home_tms(region):
    """TMs BASED at a location (the TM keys carry it as 'Name — Location')."""
    out = []
    for cfg in (_load_yaml("tm_keys.yaml").get("tms") or {}).values():
        scope = cfg.get("branches") or []
        display = cfg.get("display_name", "")
        if len(scope) == 1 and "—" in display:
            if display.split("—")[-1].strip().lower() == str(region).lower():
                out.append(scope[0])
    return sorted(out)


def _reg_filter(session, tm="", region=""):
    """SQL fragment + params limiting registrations to the session's scope.

    `tm` is the optional user-chosen Territory Manager filter (teacher/staff
    only); a TM-role session is always pinned to itself regardless.

    INVARIANT: within a location, the home-TM buckets plus "Other" partition
    every student exactly once — so the buckets always sum to the location
    total. "Other" therefore means: any TM not based at the selected location
    (visiting TMs' dealers, house accounts, blanks).
    """
    if session["role"] == "tm":
        # the demo TM key may "view as" any territory; real TM keys stay pinned
        pin = tm if (session.get("demo") and tm) else session["scope"][0]
        return "AND r.territory_manager = ?", [pin]
    if tm == "Other":
        names = _home_tms(region) if region else _real_tm_names()
        if not names:
            return "", []
        marks = ",".join("?" * len(names))
        return f"AND r.territory_manager NOT IN ({marks})", names
    if tm:
        return "AND r.territory_manager = ?", [tm]
    return "", []


def filter_options(session, region="", tm=""):
    """Dropdown values for the UI. Location is the parent cluster: the TM list
    only opens once a region is chosen, and then holds just the TMs whose
    dealers trained at that location (one branch often serves several TMs).
    A TM-role session gets only THEIR home locations (dropdown shows only when
    they manage 2+ branches)."""
    if session["role"] == "tm":
        pinned = tm if (session.get("demo") and tm) else session["scope"][0]
        home = _tm_home_region(pinned)
        return {"tms": [], "regions": [home] if home else []}
    tms = []
    if region:
        tms = _home_tms(region) + ["Other"]
    events, _, _ = load_catalog()
    regions = sorted({ev["region"] for ev in events.values() if is_active(ev)})
    return {"tms": tms, "regions": regions}


def classes_summary(session, tm="", region=""):
    """All active classes + live registration counts, scoped for the role.

    Each row carries two derived statuses (never stored):
      status_timing   past | today | upcoming        (event_date vs today)
      status_grading  graded | needs_grading | n/a   (past classes only — graded
                      when every student has attendance + a pass/fail or score)
    Optional filters: `tm` scopes the student counts, `region` drops classes
    held elsewhere.
    """
    events, _, _ = load_catalog()
    where, params = _reg_filter(session, tm, region)
    # a TM's class list = classes AT THE BRANCHES THEY MANAGE (their dealers'
    # away-games still count in dealer stats, but the schedule is theirs)
    tm_region = ""
    if session["role"] == "tm":
        pinned = tm if (session.get("demo") and tm) else session["scope"][0]
        tm_region = _tm_home_region(pinned)
    con = _con()
    counts = {row["event_id"]: row for row in con.execute(
        f"""SELECT r.event_id, COUNT(DISTINCT r.id) AS regs,
                   COALESCE(SUM(r.num_attending), 0) AS students
            FROM registrations r WHERE 1=1 {where} GROUP BY r.event_id""", params)}
    sent_log = {row["event_id"]: row["surveys_sent_at"]
                for row in con.execute("SELECT event_id, surveys_sent_at FROM class_log")}
    # grading status is a CLASS fact — computed over ALL students, never scoped,
    # so a ✅ class is ✅ for every role (teacher, staff, TM alike)
    grading = {row["event_id"]: row for row in con.execute(
        """SELECT r.event_id, COUNT(a.id) AS total,
                   SUM(CASE WHEN a.attended IS NOT NULL
                            AND (a.passed IS NOT NULL OR a.score IS NOT NULL)
                       THEN 1 ELSE 0 END) AS graded
            FROM registration_attendees a JOIN registrations r ON a.registration_id = r.id
            GROUP BY r.event_id""")}
    totals = {row["event_id"]: row["students"] for row in con.execute(
        """SELECT r.event_id, COALESCE(SUM(r.num_attending), 0) AS students
           FROM registrations r GROUP BY r.event_id""")}
    con.close()
    today = date.today().isoformat()
    out = []
    for ev in sorted(events.values(), key=lambda e: str(e.get("event_date"))):
        if not is_active(ev):
            continue
        if region and ev.get("region") != region:
            continue
        if tm_region and str(ev.get("region", "")).lower() != tm_region.lower():
            continue
        eid = ev["event_id"]
        ev_date = str(ev.get("event_date", ""))[:10]
        timing = "past" if ev_date < today else "today" if ev_date == today else "upcoming"
        g = grading.get(eid)
        if timing != "past":
            status_grading = "n/a"
        elif not g or not g["total"]:
            status_grading = "n/a"          # nobody registered — nothing to grade
        elif g["graded"] == g["total"]:
            status_grading = "graded"       # green check
        else:
            status_grading = "needs_grading"  # yellow dot
        c = counts.get(eid)
        out.append({
            "graded_count": g["graded"] if g else 0,
            "graded_total": g["total"] if g else 0,
            "surveys_sent_at": sent_log.get(eid, ""),
            "event_id": eid, "topic": ev["topic"], "region": ev["region"],
            "branch": ev["branch"], "event_date": ev_date,
            "start_time": str(ev.get("start_time", ""))[:5],
            "end_time": str(ev.get("end_time", ""))[:5],
            "capacity": ev.get("capacity"), "notes": ev.get("notes", ""),
            "registrations": c["regs"] if c else 0,
            "students": c["students"] if c else 0,
            "students_total": totals.get(eid, 0),
            "status_timing": timing, "status_grading": status_grading,
        })
    return out


# topic → badge level (mirror of tools/make_events_2026.py)
LEVELS = {
    "FIT INSTALL & COMMISSIONING": "Level 1",
    "MINI SPLIT INSTALL": "Level 2",
    "DUCTLESS SERVICE & TROUBLESHOOTING": "Level 2",
    "HEAT PUMP DIAGNOSTICS": "Level 3",
    "AIR FLOW & DUCT DESIGN": "Level 3",
    "DAIKIN FINANCING & SALES TOOLS": "Sell Track",
    "RUUD PRODUCT ESSENTIALS": "Sell Track",
}
LEVEL1_TOPIC = "FIT INSTALL & COMMISSIONING"


def _flat(session, tm="", region=""):
    """One row per student per class — the base 'df' every metric derives from."""
    where, params = _reg_filter(session, tm, region)
    if region:
        where += " AND e.region = ?"
        params = params + [region]
    con = _con()
    rows = con.execute(
        f"""SELECT a.person_id, a.name, a.role, a.attended, a.passed, a.score,
                   r.event_id, r.territory_manager, r.contact_email, r.created_at,
                   co.name AS company, co.account_number,
                   e.topic, e.region, e.event_date
            FROM registration_attendees a
            JOIN registrations r ON a.registration_id = r.id
            LEFT JOIN companies co ON r.company_id = co.id
            LEFT JOIN events e ON r.event_id = e.event_id
            WHERE 1=1 {where}""", params).fetchall()
    con.close()
    return [dict(r) for r in rows]


def _pct(n, d):
    return round(n / d, 3) if d else 0.0


def progress(session, tm="", region=""):
    """Role-shaped analytics payload for the Progress Cards view.

    Everything is derived live from the flat student×class rows — the same three
    'dataframes' every time: per-student, per-dealer, per-class. `tm`/`region`
    narrow every table and every card the same way.
    """
    rows = _flat(session, tm, region)
    today = date.today().isoformat()
    past = [r for r in rows if str(r["event_date"] or "")[:10] < today]

    # ---- per-student df ----------------------------------------------------
    # identity = people.person_id — one student,
    # one row, every profile. Name+company only as a fallback for legacy rows.
    students = {}
    for r in rows:
        key = r["person_id"] or (r["name"], r["company"])
        s = students.setdefault(key, {
            "person_id": r["person_id"],
            "name": r["name"], "company": r["company"], "role": r["role"],
            "registered": 0, "attended": 0, "passed": 0, "scores": [],
            "levels": set(), "last_class": "", "contact_email": "", "tm": "", "_latest": "",
        })
        s["registered"] += 1
        if str(r["created_at"] or "") >= s["_latest"]:
            s["_latest"] = str(r["created_at"] or "")
            s["contact_email"] = r["contact_email"] or ""
            s["tm"] = r["territory_manager"] or "Other"
        is_past = str(r["event_date"] or "")[:10] < today
        if is_past and r["attended"] == 1:
            s["attended"] += 1
            s["last_class"] = max(s["last_class"], str(r["event_date"])[:10])
            if r["passed"] == 1:
                s["passed"] += 1
                s["levels"].add(LEVELS.get(r["topic"], ""))
            if r["score"] is not None:
                s["scores"].append(r["score"])
    student_rows = sorted(({
        "person_id": s["person_id"],
        "contact_email": s["contact_email"], "tm": s["tm"],
        "name": s["name"], "company": s["company"], "role": s["role"],
        "registered": s["registered"], "attended": s["attended"], "passed": s["passed"],
        "avg_score": round(sum(s["scores"]) / len(s["scores"]), 1) if s["scores"] else None,
        "levels": sorted(l for l in s["levels"] if l),
        "last_class": s["last_class"],
        "attendance_rate": _pct(s["attended"],
                                sum(1 for r in past
                                    if (r["person_id"] or (r["name"], r["company"])) ==
                                       (s["person_id"] or (s["name"], s["company"])))),
    } for s in students.values()), key=lambda x: (-x["attended"], x["name"]))

    # ---- per-class df --------------------------------------------------------
    classes = classes_summary(session, tm, region)
    by_event = {}
    for r in past:
        b = by_event.setdefault(r["event_id"], {"attended": 0, "passed": 0, "scores": [], "total": 0})
        b["total"] += 1
        if r["attended"] == 1:
            b["attended"] += 1
            if r["passed"] == 1:
                b["passed"] += 1
            if r["score"] is not None:
                b["scores"].append(r["score"])
    for c in classes:
        b = by_event.get(c["event_id"])
        if not b or c["status_grading"] != "graded":
            # needs_grading / n-a: no partial numbers — rates exist only once the
            # trainer has graded the whole class
            c["attended"] = None
            c["attendance_rate"] = c["pass_rate"] = c["avg_score"] = None
            continue
        c["attended"] = b["attended"]
        c["attendance_rate"] = _pct(b["attended"], b["total"])
        c["pass_rate"] = _pct(b["passed"], b["attended"]) if b["attended"] else None
        c["avg_score"] = (round(sum(b["scores"]) / len(b["scores"]), 1)
                          if b["scores"] else None)

    # ---- per-dealer df -------------------------------------------------------
    real_tms = set(_real_tm_names())
    dealers = {}
    for r in rows:
        d = dealers.setdefault(r["company"] or "—", {
            "company": r["company"] or "—", "account_number": r["account_number"] or "",
            "tm": (r["territory_manager"] if r["territory_manager"] in real_tms else "Other"),
            "students": set(), "registered": 0, "scores": [],
            "attended": 0, "level1_passed": 0, "last_activity": "",
            "contact_email": "", "_latest": "",
            "last_topic": "", "last_event_date": "", "last_region": "",
        })
        d["students"].add(r["name"])
        d["registered"] += 1
        if str(r["created_at"] or "") >= d["_latest"]:
            d["_latest"] = str(r["created_at"] or "")
            d["contact_email"] = r["contact_email"] or ""
        is_past = str(r["event_date"] or "")[:10] < today
        if is_past and str(r["event_date"] or "")[:10] >= d["last_event_date"]:
            d["last_topic"], d["last_event_date"] = r["topic"] or "", str(r["event_date"])[:10]
            d["last_region"] = r["region"] or ""
        if is_past and r["attended"] == 1:
            d["attended"] += 1
            d["last_activity"] = max(d["last_activity"], str(r["event_date"])[:10])
            if r["score"] is not None:
                d["scores"].append(r["score"])
            if r["passed"] == 1 and r["topic"] == LEVEL1_TOPIC:
                d["level1_passed"] += 1
    dealer_rows = sorted(({
        **{k: v for k, v in d.items() if k not in ("scores", "_latest")},
        "students": len(d["students"]),
        "avg_score": round(sum(d["scores"]) / len(d["scores"]), 1) if d["scores"] else None,
        "engaged": d["attended"] > 0, "level1_covered": d["level1_passed"] > 0,
    } for d in dealers.values()), key=lambda x: (-x["attended"], -x["registered"]))

    # ---- summary cards -------------------------------------------------------
    past_attended = sum(1 for r in past if r["attended"] == 1)
    summary = {
        "students_total": len(student_rows),
        "registrations_total": len(rows),
        "attendance_rate": _pct(past_attended, len(past)),
        "completion_rate": _pct(sum(1 for r in past if r["passed"] == 1), past_attended),
        "returning_rate": _pct(sum(1 for s in student_rows if s["registered"] >= 2),
                               len(student_rows)),
        "past_classes": sum(1 for c in classes if c["status_timing"] == "past"),
        "today_classes": sum(1 for c in classes if c["status_timing"] == "today"),
        "upcoming_classes": sum(1 for c in classes if c["status_timing"] == "upcoming"),
        "dealers_total": len(dealer_rows),
        "dealers_engaged": sum(1 for d in dealer_rows if d["engaged"]),
        "level1_coverage": _pct(sum(1 for d in dealer_rows if d["level1_covered"]),
                                len(dealer_rows)),
    }
    topic_att = {}
    for r in past:
        if r["attended"] == 1:
            topic_att[r["topic"]] = topic_att.get(r["topic"], 0) + 1
    summary["top_topic"] = max(topic_att, key=topic_att.get) if topic_att else "—"

    out = {"role": session["role"], "summary": summary, "classes": classes,
           "filters": filter_options(session, region, tm)}
    if session["role"] == "teacher":
        out["students"] = student_rows[:80]
        out["at_risk"] = [s for s in student_rows
                          if s["registered"] >= 1 and s["attendance_rate"] < 0.5
                          and any(str(r["event_date"] or "")[:10] < today
                                  and (r["person_id"] or (r["name"], r["company"])) ==
                                      (s["person_id"] or (s["name"], s["company"]))
                                  for r in rows)][:25]
    elif session["role"] == "tm":
        out["dealers"] = dealer_rows
        out["students"] = student_rows[:80]   # same per-student df, scoped to their dealers
        # status-typed gap list: never attended → "gap flagged"; attended but
        # averaging ≤70 → "needs refresher". One Nudge button serves both.
        at_risk = []
        for d in dealer_rows:
            if not d["engaged"]:
                at_risk.append({**d, "status": "no attendance", "nudge_type": "gap"})
            elif d["avg_score"] is not None and d["avg_score"] <= 70:
                at_risk.append({**d, "status": "needs refresher", "nudge_type": "refresher"})
        out["at_risk"] = at_risk[:25]
        con = _con()
        out["nudges"] = [dict(r) for r in con.execute(
            """SELECT company, nudge_type, sent_at FROM nudge_log
               WHERE tm_id = ? ORDER BY id DESC LIMIT 12""", (session["id"],))]
        con.close()
    else:  # staff
        regions, topics = {}, {}
        for r in rows:
            is_past = str(r["event_date"] or "")[:10] < today
            for bucket, key in ((regions, r["region"] or "—"), (topics, r["topic"] or "—")):
                g = bucket.setdefault(key, {"registered": 0, "attended": 0, "passed": 0, "past": 0})
                g["registered"] += 1
                if is_past:
                    g["past"] += 1
                    if r["attended"] == 1:
                        g["attended"] += 1
                        if r["passed"] == 1:
                            g["passed"] += 1
        out["at_risk"] = [s for s in student_rows
                          if s["registered"] >= 1 and s["attendance_rate"] < 0.5
                          and any(str(r["event_date"] or "")[:10] < today
                                  and (r["person_id"] or (r["name"], r["company"])) ==
                                      (s["person_id"] or (s["name"], s["company"]))
                                  for r in rows)][:25]
        out["regions"] = sorted(({"name": k, **v,
                                  "attendance_rate": _pct(v["attended"], v["past"]),
                                  "pass_rate": _pct(v["passed"], v["attended"])}
                                 for k, v in regions.items()),
                                key=lambda x: -x["registered"])
        out["topics"] = sorted(({"name": k, **v,
                                 "attendance_rate": _pct(v["attended"], v["past"]),
                                 "pass_rate": _pct(v["passed"], v["attended"])}
                                for k, v in topics.items()),
                               key=lambda x: -x["registered"])
        out["students"] = student_rows[:80]
    return out


def finalize_class(session, event_id):
    """The trainer's send-off: queue the Day-1 checkup AND close out grading.

    Demo behavior: any still-ungraded student gets plausible completion marks so
    the class flips 🟡 → ✅ live on every dashboard. (At go-live this only
    validates completeness + triggers the real sender — it never invents grades.)
    """
    if session["role"] != "teacher":
        return {"ok": False, "error": "Only trainers can close out a class."}
    import random
    from datetime import datetime
    rng = random.Random(event_id)
    con = _con()
    rows = con.execute(
        """SELECT a.id FROM registration_attendees a
           JOIN registrations r ON a.registration_id = r.id
           WHERE r.event_id = ? AND (a.attended IS NULL
                 OR (a.passed IS NULL AND a.score IS NULL))""", (event_id,)).fetchall()
    now = datetime.now().isoformat(timespec="seconds")
    for r in rows:
        attended = rng.random() < 0.88          # realistic: a few no-shows, never 100%
        score = rng.randint(55, 96) if attended else None
        passed = 1 if (attended and score >= 70) else 0
        con.execute(
            """UPDATE registration_attendees SET attended=?, passed=?, score=?,
               comment=?, graded_by=?, graded_at=? WHERE id=?""",
            (1 if attended else 0, passed, score,
             "Completed — closed out at survey send (demo)" if attended else "No show",
             session["id"], now, r["id"]))
    con.commit()
    total = con.execute(
        """SELECT COUNT(a.id) FROM registration_attendees a
           JOIN registrations r ON a.registration_id = r.id WHERE r.event_id = ?""",
        (event_id,)).fetchone()[0]
    con.close()
    return {"ok": True, "filled": len(rows), "total": total,
            "message": f"Class closed out — {total} students graded, surveys queued (simulated)."}


def roster(session, event_id, tm=""):
    """Per-student rows for one class, scoped for the role. Read-only data —
    the grading fields exist only in the browser during the demo."""
    where, params = _reg_filter(session, tm)
    con = _con()
    rows = con.execute(
        f"""SELECT a.id AS attendee_id, a.name, a.role, a.is_returning,
                   a.attended, a.passed, a.score, a.comment, a.graded_by, a.graded_at,
                   c.name AS company_name, c.account_number,
                   r.branch, r.territory_manager, r.contact_email, r.created_at
            FROM registration_attendees a
            JOIN registrations r ON a.registration_id = r.id
            LEFT JOIN companies c ON r.company_id = c.id
            WHERE r.event_id = ? {where}
            ORDER BY c.name, a.name""", [event_id] + params).fetchall()
    con.close()
    return [dict(r) for r in rows]
